---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: media
  label: Media
  config:
    required: true
- type: text
  label: Year
  name: year
  config:
    required: true
- type: image_gallery
  name: images
  label: Images
- type: text
  name: category
  label: category
  description: 'eg: projects'
  default: projects
pages:
- _posts/2019-03-18-break.md
- _posts/2019-03-18-untitled.md
- _posts/2019-06-28-why-are-you-showing-me-that-again.md
- _posts/2020-09-05-assembly.md
- _posts/2020-09-05-the-recreation-myth.md
- _posts/drive-in.md
